### ISSUE TITLE
Reformat data instructions

### ISSUE THREAD

**Issue by insurw** [se-fLa/filmtipset2trakt#1]
This is wrong it seems:
tr -d '\r' < Filmtipset.tsv > **Filmtipset_Alla_betyg.xls**

It should be a different named TSV file, e.g:
tr -d '\r' < **Filmtipset-org.tsv** > **Filmtipset.tsv**
awk -F"\t" '{print "tt" $7 "," $6}' Filmtipset.tsv > Filmtipset_movies.csv
awk -F"\t" '{print "tt" $7 "," $5 "," $6}' Filmtipset.tsv > Filmtipset_ratings.csv

What awk goes is easy to understand even if you don't know any Bash. But tr -d I had to look up (it removes carriage return (CR) in this case). Maybe write what the commands actually do?

Also I'd suggest using Bash in Win10. It was quite easy to install.
http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

**Comment by se-fLa** [comment]
Thank you for pointing this out, I have corrected and improved the documentation. These changes are merged to master.
