### ISSUE TITLE
Filmtipset rating 1 becomes rating 2 on Trakt

### ISSUE THREAD

**Issue by insurw** [se-fLa/filmtipset2trakt#4]
Even though it says in the code:
> make the rating a number and also change from 1-5 to 1-10

But instead the rating is just duplicated
`rating = int(row["rating"]) * 2`

Fixed by changing the `rating = int(row["rating"])` line (92) and adding an IF statement to syncFromCsvFile.py:

```
elif operation == "rate":
      # make the rating a number and also change from 1-5 to 1-10
      rating = int(row["rating"])
      if rating > 1:
         rating = rating*2
      movie = { "rated_at": row["at"], "rating": rating, "ids": { "imdb": row["imdb"] } }
```

**Comment by se-fLa** [comment]
Indeed you are correct. I have corrected the comment and added info to the usage info to state 1-5 becomes 2-10. These changes has been pushed to master.
