### ISSUE TITLE
The ratings don't match Trakt.tv ratings

### ISSUE THREAD

**Issue by bengt-a** [se-fLa/filmtipset2trakt#5]
Hi,
When uploading the ratings, they are uploaded as the Filmtipset ratings, i.e. from 1-5. But Trakt.tv uses another scale, from 1-10. This makes the ratings upload incorrect. E.g. a movie with a rating of 4 on Filmtipset (Good) will end up being a 4 on Trakt.tv (Poor).

While converting the files and creating the csv files, it would be easiest if the Filmtipset ratings were simply doubled. 

Suggestion to improve the awk command in the instructions:
`awk -F"\t" '{print "tt" $7 "," $5*2 "," $6}' Filmtipset-unix.tsv > Filmtipset_ratings.csv`

**Comment by se-fLa** [comment]
No, from the Readme you can find that it is taken care of by the program:
"All ratings will be doubled, e.g the script converts from rating scale 1-5 to 2-10."

**Comment by bengt-a** [comment]
Double checking the ratings, apparently I must have done some mistake when reviewing the ratings. My bad. Nothing is wrong. Can I delete this thread somehow?

**Comment by se-fLa** [comment]
You must have done something wrong, it's tested and verified. If you can reproduce it describe the steps in a bugreport.
